language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - hhvm

before_script:
    - composer --dev install
    - lscpu

script:
    - bin/karzer --threads=8 src/Karzer/Tests/Functional/SleepTest.php
    - bin/karzer --threads=4 src/Karzer/Tests/Functional/SleepTest.php
    - bin/karzer --threads=2 src/Karzer/Tests/Functional/SleepTest.php
    - bin/karzer --threads=1 src/Karzer/Tests/Functional/SleepTest.php
