language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6

before_script:
    - composer --dev install

script:
    - bin/karzer --threads=8 src/Karzer/Tests/Functional/SleepTest.php
    - bin/karzer --threads=4 src/Karzer/Tests/Functional/SleepTest.php
    - bin/karzer --threads=2 src/Karzer/Tests/Functional/SleepTest.php
    - bin/karzer --threads=1 src/Karzer/Tests/Functional/SleepTest.php
