#!/usr/bin/env php
<?php

use Karzer\PHPUnit\TextUI\Command;

define('PHPUnit_MAIN_METHOD', 'PHPUnit_TextUI_Command::main');

$files = [
    __DIR__ . '/../../autoload.php',
    __DIR__ . '/../vendor/autoload.php',
    __DIR__ . '/vendor/autoload.php',
];

foreach ($files as $file) {
    if (file_exists($file)) {
        define('PHPUNIT_COMPOSER_INSTALL', $file);
        break;
    }
}

unset($file);

if (!defined('PHPUNIT_COMPOSER_INSTALL')) {
    die(
      'You need to set up the project dependencies using the following commands:' . PHP_EOL .
      'curl -s http://getcomposer.org/installer | php' . PHP_EOL .
      'php composer.phar install' . PHP_EOL
    );
}

require PHPUNIT_COMPOSER_INSTALL;
require_once __DIR__ . '/monkeyPatch.php';

Command::main();
